from django.core.management.base import BaseCommand
from base.models import ListKhodam

class Command(BaseCommand):
    help = 'Insert khodam data into ListKhodam'

    def handle(self, *args, **kwargs):
        khodam_data = [
            'Buaya Putih',
            'Kuda Nil',
            'Kupu-Kupu Hitam',
            'Buah Jambu',
            'Macan Salto',
            'Macan Hitam',
            'Macan Putih',
            'Rusa',
            'Kura-Kura',
            'Kupu-Kupu Laut',
            'Kapal Laut',
            'Serigala Gunung',
            'Kura-Kura Hitam',
            'Kura-Kura Merah',
            'Kura-Kura Salto',
            'Unta Hamil',
            'Macan Tutul',
            'Angsa Pink',
            'Banteng Merah',
            'Banteng Hitam',
            'Kambing Satan',
            'Kambing Hitam',
            'Burung Hantu',
            'Burung Merak',
            'Elang Emas',
            'Gajah Putih',
            'Harimau Jawa',
            'Ikan Duyung',
            'Ikan Hiu',
            'Kijang Kencana',
            'Kucing Hutan',
            'Kucing Hitam',
            'Leopard Biru',
            'Lumba-Lumba',
            'Naga Hijau',
            'Naga Merah',
            'Naga Biru',
            'Singa Putih',
            'Srigala Hitam',
            'Srigala Putih',
            'Tikus Hitam',
            'Tikus Putih',
            'Ular Kobra',
            'Ular Sanca',
            'Ular Piton',
            'Ular Hijau',
            'Ular Merah',
            'Zebra Emas',
            'Burung Pipit',
            'Burung Gereja',
            'Burung Kakaktua',
            'Burung Nuri',
            'Kelinci Putih',
            'Kelinci Hitam',
            'Kelinci Merah',
            'Kelinci Kuning',
            'Kuda Putih',
            'Kuda Hitam',
            'Kuda Merah',
            'Kuda Biru',
            'Bebek Putih',
            'Bebek Hitam',
            'Bebek Kuning',
            'Bebek Merah',
            'Angsa Hitam',
            'Angsa Merah',
            'Angsa Kuning',
            'Angsa Biru',
            'Babi Hutan',
            'Babi Putih',
            'Babi Hitam',
            'Babi Merah',
            'Gajah Hitam',
            'Gajah Merah',
            'Gajah Biru',
            'Gajah Kuning',
            'Harimau Putih',
            'Harimau Hitam',
            'Harimau Merah',
            'Harimau Kuning',
            'Elang Putih',
            'Elang Hitam',
            'Elang Merah',
            'Elang Kuning',
            'Leopard Putih',
            'Leopard Hitam',
            'Leopard Merah',
            'Leopard Kuning',
            'Lumba-Lumba Putih',
            'Lumba-Lumba Hitam',
            'Lumba-Lumba Merah',
            'Lumba-Lumba Kuning',
            'Naga Putih',
            'Naga Hitam',
            'Naga Merah',
            'Naga Kuning',
            'Singa Hitam',
            'Singa Merah',
            'Singa Kuning',
            'Singa Biru',
            'Srigala Merah',
            'Srigala Kuning',
            'Srigala Biru',
            'Tikus Merah',
            'Tikus Kuning',
            'Tikus Biru',
            'Ular Putih',
            'Ular Hitam',
            'Ular Biru',
            'Ular Kuning',
            'Zebra Putih',
            'Zebra Hitam',
            'Zebra Merah',
            'Zebra Kuning',
            'Ayam Putih',
            'Ayam Hitam',
            'Ayam Merah',
            'Ayam Kuning',
            'Ayam Biru',
            'Pisang',
            'Piring Pecah',
            'ChagGPT',
            'Singa Hamil 1 Abad',
            'Singa Hamil 2 Abad',
            'Singa Bersayap',
            'Alucard Kalah Retri',
            'Minion',
            'Buff Ungu',
            'Buff Oranye',
            'Turet Base',
            'Sabun Bolong',
            'Opet',
            'Garpu',
            'Penghapus',
            'Penggaris',
            'Cincin Mantan',
            'Cincin Pacar',
            'Cincin Selingkuhan',
            'Tas',
            'Tas Besi',
            'Tas Kaca',
            'Tas Plastik',
            'Tas Pita',
            'Tas Gunting',
            'Buaya Darat',
            'Buaya Laut',
            'Buaya Air',
            'Buaya Udara',
            'Pocong Lari',
            'Pocong Terbang',
            'Pocong Lompat',
            'Kuntilanak Kawin',
            'Mantan Temen',
            'Pintu',
            'Jendela',
            'Pagar',
            'Kaca',
            'Kotak',
            'Tiang',
            'Pipa',
            'Keramik',
            'Laci',
            'Lemari',
            'Rak',
            'Sepatu',
            'bor',
            'Mimi Peri',
            'Naga Salto',
            'Keranjang Rusak',
            'Burung Hantu',
            'Elang Laut',
            'Jinn',
            'Phoenix',
            'Dragon',
            'Mermaid',
            'Griffin',
            'Sphinx',
            'Fairy',
            'Centaur',
            'Leprechaun',
            'Pegasus',
            'Unicorn',
            'Genie',
            'Basilisk',
            'Kelpie',
            'Gembok',
            'Salamander',
            'Werewolf',
            'Vampire',
            'Ghost',
            'Spirit',
            'Elemental',
            'Golem',
            'Tengu',
            'Kitsune',
            'Djinn',
            'Nymph',
            'Elf',
            'Sprite',
            'Satyr',
            'Wraith',
            'Poltergeist',
            'Chimera',
            'Yeti',
            'Kraken',
            'Cyclops',
            'Gorgon',
            'Minotaur',
            'Thunderbird',
            'Banshee',
            'Lamia',
            'Wendigo',
            'Chupacabra',
            'Siren',
            'Cerberus',
            'Necromancer',
            'Ninja',
            'Vampire Bat',
            'Zombie',
            'Cursed',
            'Skeleton',
            'Witch',
            'Cultist',
            'Cult Leader',
            'Cult Fanatic',
            'Cult Leader',
            'Pocong Kejepit',
            'Kereta Api',
            'Pesawat Laut',
            'Kapal Selam Darat',
            'Kapal Selam Laut',
            'Zilong Roam',
            'Guru BK',
            'Guru Penjas',
        ]

        unique_khodam_data = list(set(khodam_data))

        khodam_instances = [ListKhodam(nama_khodam=name) for name in unique_khodam_data]

        ListKhodam.objects.bulk_create(khodam_instances)
        self.stdout.write(self.style.SUCCESS('Successfully inserted khodam data'))
