# Generated by Django 5.0.6 on 2024-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListKhodam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_khodam', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
