# Generated by Django 5.0.6 on 2024-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('khodam', models.CharField(blank=True, max_length=255, null=True)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
